### ISSUE TITLE
Random player colors are too hard to distinguish

### ISSUE THREAD

**Issue by BytewaveMLP** [NotMyWing/GarrysModAmongUs#2]
This is a two-fold issue:

- The playermodels used don't apply colors properly, and the lighting of the test map further compounds the issue
- Randomly-generated colors are too prone to being too close together

**Comment by NotMyWing** [comment]
This should be fixed alongside #6 by introducing proper, curated color palletes.

**Comment by NotMyWing** [comment]
Finally fixed in https://github.com/NotMyWing/GarrysModAmongUs/commit/9e36b91d801c1c9c31f9cc00457bab1d28174072. I forgot a closing keyword.

**Comment by NotMyWing** [comment]
Well, actually not quite.

**Comment by NotMyWing** [comment]
Now it is.
