### ISSUE TITLE
Dynamic light inside player causes improper lighting on prop_static

### ISSUE THREAD

**Issue by BytewaveMLP** [NotMyWing/GarrysModAmongUs#29]
When the player approaches a prop in the map, the `DynamicLight` created at their viewpoint causes the prop to suddenly "pop" in brightness, leading to some rather distracting visuals. This can be fixed either by setting `nomodel = true` on the `DynamicLight` table, or by removing the dynamic light system entirely it shouldn't be necessary now, with the new method for limiting view and properly-lit maps.

**Comment by NotMyWing** [comment]
I'm honestly thinking that it's time to remove dynamic lights completely since we settled on a different way of implementing limited vision.
