### ISSUE TITLE
Unpredictable overly-aggressive culling on func_task_buttons

### ISSUE THREAD

**Issue by BytewaveMLP** [NotMyWing/GarrysModAmongUs#34]
Occasionally, for the first round or so after joining a server, clients may experience an issue where `func_task_button`s disappear when their origin is moved off-screen. This occurs consistently for the first round or so of gameplay, before suddenly behaving again. More investigation is needed into the exact reproduction steps and causes. This issue does not seem to appear as a listen server host.

**Comment by NotMyWing** [comment]
This can be potentially caused by https://github.com/NotMyWing/GarrysModAmongUs/blob/b0fbfc5699cd2450d7c2fe8f7d8fa1957a9dbbaf/moon/amongus/entities/entities/func_task_button.moon#L17

Though I can't be sure because I'm not able to reproduce this myself.
