### ISSUE TITLE
Player color weirdness

### ISSUE THREAD

**Issue by BytewaveMLP** [NotMyWing/GarrysModAmongUs#41]
After 1f12214da8b521c117707bc4c32a9b82d16aab4b, a couple of things were missed:

- One hanging reference to `SetColor`, causing player colors to be set incorrectly after a game restart
https://github.com/NotMyWing/GarrysModAmongUs/blob/1f12214da8b521c117707bc4c32a9b82d16aab4b/moon/amongus/gamemode/sv_game.moon#L250
- Corpses do not correctly apply the player color for some reason.
- Ghosts do not use `SetPlayerColor`. Since ghosts need to be drawn transparently, I'm not sure if there's a good approach to fixing this. Could potentially make transparent textures for the (to-be-created ghost model)?

**Comment by NotMyWing** [comment]
Ghost translucency is already being handled pretty fine in
https://github.com/NotMyWing/GarrysModAmongUs/blob/bb3f1c4825dcd2740bcd10a1d1942336e713c792/moon%2Famongus%2Fgamemode%2Fsv_player.moon#L35-L38

**Comment by BytewaveMLP** [comment]
Right, but that still calls `SetColor`, no? So it would still have the same issue as all other instances of `SetColor`, only less noticeable since the ghost player is transparent.
