### ISSUE TITLE
Ghosts cannot talk to each other during the game

### ISSUE THREAD

**Issue by NotMyWing** [NotMyWing/GarrysModAmongUs#66]
Got broken in 950366f4ad301631ede06d3a51bb866d6e12c1b2, needs investigation.

**Comment by BytewaveMLP** [comment]
Would it perhaps be the [removal of the `IsDead` check in `PlayerSay`](https://github.com/NotMyWing/GarrysModAmongUs/commit/950366f4ad301631ede06d3a51bb866d6e12c1b2#diff-0ba56713ef064ef0f8d5ed20b4e185ea26bcb784a87aa1960436397099b1bdcdL457) that caused this? I don't recall why it was removed, if done so intentionally.

**Comment by NotMyWing** [comment]
Should be fixed in b20f8a868f29aaab1d3d9e3f5bcff54fe431eec3, however I will leave the issue open for now in case something else related to this pops up.

**Comment by NotMyWing** [comment]
Evidently this has been fixed.
